# -*- coding: utf-8 -*-
"""
build_phase1_base.py — Phase 1 of the override rebuild.

Phase 1 = the building blocks only:
  * the 35 STANDALONE single-letter overrides (ก ข ค ... -> กะ ขะ คะ ...)
  * every 1-syllable word already in the old override (จำ ได้ เป็น ใจ ...)

We deliberately DROP all 2+ syllable compound keys.  The runtime
extract_poetic_syllables() composition branch rebuilds compounds from these
parts (จำเป็น = จำ + เป็น), so storing every compound is unnecessary — and the
single-letter guard in Noto_tokenizer.py makes the 1-char keys standalone-only.

Usage:
    python build_phase1_base.py          # writes poetry_overrides_base.py
"""
import sys

sys.stdout.reconfigure(encoding="utf-8")

SRC = "poetry_overrides.py"
OUT = "poetry_overrides_base.py"


def load(src):
    ns = {}
    exec(compile(open(src, encoding="utf-8").read(), src, "exec"), ns)
    return ns["POETRY_OVERRIDES"]


def main():
    old = load(SRC)
    singles = {}
    one_syl = {}
    for k, v in old.items():
        if len(k) == 1:
            singles[k] = v                      # standalone-only letters
        elif len(v) == 1:
            one_syl[k] = v                      # 1-syllable common words

    dropped = len(old) - len(singles) - len(one_syl)
    print(f"old override        : {len(old):,} keys")
    print(f"  standalone singles : {len(singles):,}")
    print(f"  1-syllable words   : {len(one_syl):,}")
    print(f"  dropped (2+ syll)  : {dropped:,}")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("# -*- coding: utf-8 -*-\n")
        fh.write("# POETRY_OVERRIDES_BASE — PHASE 1 of the rebuild (generated by\n")
        fh.write("# build_phase1_base.py). NO 2+ syllable compounds: the runtime\n")
        fh.write("# composition branch rebuilds them from these parts.\n")
        fh.write("#\n")
        fh.write("#  * single letters are STANDALONE-ONLY (Noto_tokenizer.py guard):\n")
        fh.write("#    they never fire as sub-syllables inside a longer word\n")
        fh.write("#    (จวน -> จ+วน would otherwise mis-split to จะ-วน).\n")
        fh.write("POETRY_OVERRIDES_BASE = {\n")
        fh.write("    # ---- standalone single letters (standalone-only) ----\n")
        for k in singles:
            fh.write('    "%s": [%s],\n' % (k, ", ".join('"%s"' % s for s in singles[k])))
        fh.write("\n    # ---- 1-syllable common words (the composition building blocks) ----\n")
        for k in one_syl:
            fh.write('    "%s": [%s],\n' % (k, ", ".join('"%s"' % s for s in one_syl[k])))
        fh.write("}\n")
    print(f"wrote {OUT} ({len(singles) + len(one_syl):,} keys)")


if __name__ == "__main__":
    main()
